on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        otp: ['24.0']
        elixir: ['1.12.2']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Restore dependency cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-mix-
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test --warnings-as-errors 
